name: nodejs test
on: push
env:
  accessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
  secretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
jobs:
  ec2:
    strategy:
      matrix:
        module: [ ec2, kms, dynamo, s3, sqs,xray ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nodejs/${{matrix.module}}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: npm install
      - run: npm test

